### ISSUE TITLE
Memory corruption crashes when using larger font sizes with Shalassian

### ISSUE THREAD

**Issue by whisperity** [contour-terminal/contour#1065]
### Contour Terminal version

0.3.10.4591

### Installer source

Github: CI actions

### Operating System

Ubuntu 20.04

### Architecture

x86-64

### Steps to reproduce

1. Download [Shalassian](https://feyawen.carrd.co/) and set it as the regular font family, size 12.
2. Start Contour and do <kbd>Ctrl</kbd>-<kbd>MWheelUp</kbd> to increase the font size **4 times**.
3. Contour crashes.

### Expected Behavior

No crash.

### Actual Behavior

Crash, with no explanation as to what is happening. Sometimes `munmap_chunk(): Invalid pointer.`, sometimes `free(): Invalid next size (fast)`, sometimes `double free or corruption (out)`.

```
[2023-03-16 10:17:45.272049] [vt.renderer] Updating grid metrics: (pageSize=67x21, cellSize=13x16, baseline=2, underline=1@1, margin=(left=0, bottom=0))
[2023-03-16 10:17:45.272136] [font.locator] Calculating font metrics for (family=Shalassian Font weight=Bold slant=Italic spacing=Monospace, strict_spacing=no): (17, 14, 15, 0, -2, 1)
[2023-03-16 10:17:45.272140] [vt.renderer] Loading grid metrics (pageSize=67x21, cellSize=14x17, baseline=2, underline=0@1, margin=(left=0, bottom=0))
[2023-03-16 10:17:45.272310] [gui.display] configureAtlas: 2048x2048 RGBA
[2023-03-16 10:17:45.272367] [vt.renderer] Configuring texture atlas.
[2023-03-16 10:17:45.272372] [vt.renderer] - Atlas properties     : tile size 14x17, format RGBA, direct-mapped 116
[2023-03-16 10:17:45.272375] [vt.renderer] - Atlas texture size   : 2048x2048 pixels
[2023-03-16 10:17:45.272378] [vt.renderer] - Atlas hashtable      : 4096 slots
[2023-03-16 10:17:45.272381] [vt.renderer] - Atlas tile count     : 17520 = 146x * 120y
[2023-03-16 10:17:45.272384] [vt.renderer] - Atlas direct mapping : enabled (for text rendering)
[2023-03-16 10:17:45.274147] [font.locator] Loading font: key=11, id="/usr/share/fonts/truetype/noto/NotoSansMono-Bold.ttf" size=15pt dpi 96x96 (28, 12, 22, -5, -2, 1)
double free or corruption (out)
```

```
[2023-03-16 10:18:10.571811] [font.render] rasterize (11, 15pt, 97) to rasterized_glyph(0, 12x5+(0, 9), rgb)
[2023-03-16 10:18:10.571815] [vt.rasterizer] Inserting rasterized_glyph(0, 12x5+(0, 9), rgb) (bbox 14x15, numCells 1) id 97 render mode LCD Text yOverflow 0 yMin 6.
[2023-03-16 10:18:10.571820] [font.textshaping] Shaping using font key: 9, text: "$"
[2023-03-16 10:18:10.571824] [font.textshaping] Shaping codepoints (Text): 0:U+24
        Using font: key=9, path="/home/whisperity/.fonts/s/ShalassianFont_Regular.ttf"
[2023-03-16 10:18:10.571829] [font.textshaping] Try fallbacks font key:11, source: path /usr/share/fonts/truetype/noto/NotoSansMono-Bold.ttf Bold Roman
[2023-03-16 10:18:10.571834] [vt.rasterizer] Shaped codepoints (Text): $ (U+0024/0)
        with metrics: (7+0+0|12+0)
[2023-03-16 10:18:10.578060] [gui.display] Setting display font size and recompute metrics: 16pt
[2023-03-16 10:18:10.578069] [font.locator] Locating font chain for: (family=Shalassian Font weight=Regular slant=Roman spacing=Monospace, strict_spacing=no)
[2023-03-16 10:18:10.582470] [font.locator] Font 1 (ttc index 0, weight Regular, slant Roman, spacing -1) in chain: /home/whisperity/.fonts/s/ShalassianFont_Regular.ttf
[...]
[2023-03-16 10:18:10.585195] [font.locator] Font 173 (ttc index 0, weight Medium, slant Roman, spacing -1) in chain: /usr/share/fonts/truetype/fonts-orya-extra/utkal.ttf
[2023-03-16 10:18:10.585200] [font.locator] Font 174 (ttc index 0, weight Bold, slant Roman, spacing -1) in chain: /usr/share/fonts/truetype/fonts-gujr-extra/padmaa-Bold.1.1.ttf
free(): invalid next size (fast)
```

### Additional notes

Likely there is something wrong with the font itself, because Darnassian (available from the same site) is allowing to zoom in (increase font size) massively.

(Also, for some reason, font size 12 is MUCH worse with these fonts than with JetBrains Mono or some other monospace font. Are the fonts this bad or is Contour consuming something the wrong way?)

Texture atlas pre-crash:
![image](https://user-images.githubusercontent.com/1969470/225570743-b9b55b39-e3c1-47e2-b105-0bdfc4c7d7cf.png)

**Comment by uspasojevic96** [comment]
> (Also, for some reason, font size 12 is MUCH worse with these fonts than with JetBrains Mono or some other monospace font. Are the fonts this bad or is Contour consuming something the wrong way?)

Check strict spacing config flag

**Comment by whisperity** [comment]
> > (Also, for some reason, font size 12 is MUCH worse with these fonts than with JetBrains Mono or some other monospace font. Are the fonts this bad or is Contour consuming something the wrong way?)
> 
> Check strict spacing config flag

@uspasojevic96 I have it on "false" because I'm not using purely monospace fonts. I've set it to "true" but it changed nothing in particular. And the crash still happens, just this time I got a `realloc(): invalid old size` instead.

The font size is bonkers still.

![image](https://user-images.githubusercontent.com/1969470/225629490-1ddb96d7-869c-4933-bad4-41bcb5d9c805.png)

**Comment by Yaraslaut** [comment]
Can be reproduced on startup if set font size to 15. 
Crash is similar to https://github.com/contour-terminal/contour/issues/964
with backtrace 
```
* thread #1, name = 'contour', stop reason = signal SIGABRT
  * frame #0: 0x00007ffff60a08ec libc.so.6`___lldb_unnamed_symbol3539 + 268
    frame #1: 0x00007ffff6051ea8 libc.so.6`raise + 24
    frame #2: 0x00007ffff603b53d libc.so.6`abort + 215
    frame #3: 0x00007ffff62d30e2 libstdc++.so.6`std::__glibcxx_assert_fail(file=<unavailable>, line=1123, function=<unavailable>, condition=<unavailable>) at debug.cc:60:10
    frame #4: 0x000055555587ffdf contour`terminal::rasterizer::DecorationRenderer::createTileData(this=0x00005555562397b8, decoration=DashedUnderline, tileLocation=TileLocation @ 0x00007fffffffc8fc) at DecorationRenderer.cpp:0:1
    frame #5: 0x000055555587f0ea contour`terminal::rasterizer::DecorationRenderer::initializeDirectMapping(this=0x00005555562397b8) at DecorationRenderer.cpp:97:49
    frame #6: 0x0000555555868758 contour`terminal::rasterizer::Renderer::configureTextureAtlas(this=0x00005555562393a0) at Renderer.cpp:211:26
    frame #7: 0x000055555586831d contour`terminal::rasterizer::Renderer::setRenderTarget(this=0x00005555562393a0, renderTarget=0x0000555556324ac0) at Renderer.cpp:180:5
```

**Comment by christianparpart** [comment]
do you get more insight when running contour through valgrind?

**Comment by whisperity** [comment]
@Yaraslaut @contour-terminal/internal I tried with current latest master, build no. 0.3.12.4984 on Ubuntu **20**.04 and the crash is still there:

~~~~
#3  0x00007ffff64c8b39 in operator new(unsigned long) () at /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00005555557513ed in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag)
    (this=this@entry=0x7fffffffbf30, __beg=0x555557bd3430 "/home/ericsza/.config/", __end=<optimised out>) at /usr/include/c++/9/bits/char_traits.h:370
#5  0x000055555586b781 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<char*>(char*, char*, std::__false_type)
    (__end=<optimised out>, __beg=<optimised out>, this=0x7fffffffbf30) at /usr/include/c++/9/bits/basic_string.h:940
#6  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*) (__end=<optimised out>, __beg=<optimised out>, this=0x7fffffffbf30)
    at /usr/include/c++/9/bits/basic_string.h:270
#7  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    (__str="/home/ericsza/.config/", this=0x7fffffffbf30) at /usr/include/c++/9/bits/basic_string.h:455
#8  std::filesystem::__cxx11::path::path(std::filesystem::__cxx11::path const&) (__p=filesystem::path "/home/ericsza/.config/" = {...}, this=0x7fffffffbf30)
    at /usr/include/c++/9/bits/fs_path.h:175
#9  std::filesystem::__cxx11::operator/(std::filesystem::__cxx11::path const&, std::filesystem::__cxx11::path const&)
    (__rhs=filesystem::path "kcmfonts", __lhs=filesystem::path "/home/ericsza/.config/" = {...}) at /usr/include/c++/9/bits/fs_path.h:449
#10 contour::display::(anonymous namespace)::kcmFontsFilePath() () at /home/runner/work/contour/contour/src/contour/display/TerminalWidget.cpp:229
#11 0x000055555586bad7 in contour::display::TerminalWidget::contentScale() const (this=0x555555d73860) at /home/runner/work/contour/contour/src/contour/display/TerminalWidget.cpp:769
#12 0x000055555586c3e1 in contour::display::TerminalWidget::fontDPI() const (this=this@entry=0x555555d73860) at /home/runner/work/contour/contour/src/contour/display/TerminalWidget.cpp:823
#13 0x000055555586c772 in contour::display::TerminalWidget::logDisplayInfo() (this=0x555555d73860) at /home/runner/work/contour/contour/src/contour/TerminalSession.h:70
#14 0x000055555586eedd in contour::display::TerminalWidget::setFontSize(text::font_size) (this=0x555555d73860, _size=..., _size@entry=...)
    at /home/runner/work/contour/contour/src/contour/display/TerminalWidget.cpp:1077
#15 0x00005555557aa62e in contour::TerminalSession::setFontSize(text::font_size) (this=0x555555cc9160, _size=...) at /home/runner/work/contour/contour/src/contour/TerminalSession.cpp:1259
#16 0x00005555557aa69d in contour::TerminalSession::operator()(contour::actions::IncreaseFontSize) (this=<optimised out>) at /home/runner/work/contour/contour/src/text_shaper/font.h:228
~~~~

**Comment by whisperity** [comment]
Oh... wait. The fix *isn't* merged yet and I should be trying a PR build... alright... My bad.

**Comment by christianparpart** [comment]
#1087 is merged by now. Do you have time to re-test, @whisperity? :-)
