### ISSUE TITLE
Set terminal title by .Net console application throwing an exception

### ISSUE THREAD

**Issue by AugustoDeveloper** [contour-terminal/contour#1102]
### Contour Terminal version

0.3.11.258

### Installer source

GitHub: release page

### Operating System

Ubuntu 22.04.2 LTS

### Architecture

x86-64

### Other Software

NVIM v0.9.0

### Steps to reproduce

Creating a dotnet console application with:
```bash
dotnet new console 
```
That will creates a .Net application, so just edit the file `Program.cs`:
```csharp
Console.Title = "Test"
```

And run it:

```bash
dotnet run
```

### Expected Behavior

The behavior expected is the name of console changes the bottom title bar:

Before execution:
![image](https://github.com/contour-terminal/contour/assets/4335700/e2f2193d-a249-46bf-a216-4e9922fc1693)

After execution:

![image](https://github.com/contour-terminal/contour/assets/4335700/a8f2ab44-f92a-45f5-b473-2887fb0e8435)

### Actual Behavior

Throwing an exception:
```c#
Unhandled exception. System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Pop()
   at System.TermInfo.ParameterizedStrings.EvaluateInternal(String format, Int32& pos, FormatParam[] args, Stack`1 stack, FormatParam[]& dynamicVars, FormatParam[]& staticVars)
   at System.TermInfo.ParameterizedStrings.Evaluate(String format, FormatParam[] args)
   at System.ConsolePal.set_Title(String value)
```
![image](https://github.com/contour-terminal/contour/assets/4335700/e17cda35-7496-42ad-9865-44f7fd4ed3b2)

**Comment by Yaraslaut** [comment]
Looks like something is wrond with terminfo file, can you check what is `echo $TERM` telling you? 
First thing that you can try is to set same TERM (`export TERM=....`) for contour as for gnome-terminal, and see if this will resolve issue, then we can identify what we need to fix exactly.

**Comment by uspasojevic96** [comment]
I can't reproduce it on latest master 
![image](https://github.com/contour-terminal/contour/assets/3018800/6523a4fb-27f5-419b-b2ce-048cb82ea431)

**Comment by AugustoDeveloper** [comment]
Exporting variable as 'x-term-256color', as gnome-terminal, it works!

The value before export was 'contour'

Thanks @Yaraslaut

**Comment by AugustoDeveloper** [comment]
> Looks like something is wrond with terminfo file, can you check what is `echo $TERM` telling you? 
> 
> First thing that you can try is to set same TERM (`export TERM=....`) for contour as for gnome-terminal, and see if this will resolve issue, then we can identify what we need to fix exactly.

Exporting variable as 'x-term-256color', as gnome-terminal, it works!

The value before export was 'contour'

Thanks @Yaraslaut

**Comment by AugustoDeveloper** [comment]
> I can't reproduce it on latest master 
> 
> ![image](https://github.com/contour-terminal/contour/assets/3018800/6523a4fb-27f5-419b-b2ce-048cb82ea431)
> 
> 

At my last reply, the env var $TERM was setted as 'contour', can you check if it is setted different in your machine to reproduce same erro?

**Comment by uspasojevic96** [comment]
![image](https://github.com/contour-terminal/contour/assets/3018800/7a589d4a-cf3b-4269-8077-e38f307feadd)
default contour config

**Comment by Yaraslaut** [comment]
@AugustoDeveloper  by default contour install terminfo file in `/usr/local/share/terminfo/c` directory.
in `man tic` we can see
```

       Libraries that read terminfo entries are expected to check in succession

       •   a location specified with the TERMINFO environment variable,

       •   $HOME/.terminfo,

       •   directories listed in the TERMINFO_DIRS environment variable,

       •   a compiled-in list of directories (no default value), and

       •   the system terminfo database (/usr/share/terminfo).
```
so you need to take care of this, for example you can just copy files in `/usr/share/terminfo/c` folder

@christianparpart can we somehow figure out how to handle this properly?

**Comment by uspasojevic96** [comment]
We can update the install script to symlink stuff to /usr/share/terminfo/c BUT i believe packages do get installed in proper places instead of /usr/local/

**Comment by Yaraslaut** [comment]
> We can update the install script to symlink stuff to /usr/share/terminfo/c BUT i believe packages do get installed in proper places instead of /usr/local/

indeed, for packages  `local` is not used and its directly `/usr/share/terminfo` issue is that we have packages for arch and fedora only, so people on ubuntu is in disadvantage

**Comment by uspasojevic96** [comment]
We could append to `$TERMINFO_DIRS`

**Comment by Yaraslaut** [comment]
but it will depend on a  SHELL that people are using, right ? 
and not all of the shells make source of bashrc for example

**Comment by uspasojevic96** [comment]
Doesn't matter, we can append to ENV through cpp

**Comment by christianparpart** [comment]
When building manually, the `CMAKE_INSTALL_PREFIX` defaults to `/usr/local`, that is why **everything** will be prefix-installed into that directory. 

`terminfo/c/contour` will be installed into `CMAKE_INSTALL_DATADIR` which defaults to `CMAKE_INSTALL_DATAROOTDIR`, which by default is set to `share` (relative to and is `CMAKE_INSTALL_PREFIX`).

One could configure cmake by passing a custom `CMAKE_INSTALL_DATADIR` to tweak where `share`-data is installed, but that would also install other share-data then. If it's not an official package (which usually go into `/usr` then I just suggest to install wherever you want (e.g. leave it like the default) but then create a symlink by making use of the fact that terminfo library looks into `$HOME/.terminfo`, so either copying `/usr/local/share/terminfo/c/contour` into `$HOME/.terminfo/c/contour` or create a symlink of `/usr/local/share/terminfo` to `$HOME/.terminfo`.

I know that it isn't perfect, but terminfo is inherently flawed. We have to sadly live with that. :)

@AugustoDeveloper, please keep us posted if you need any support here.

**Comment by uspasojevic96** [comment]
@christianparpart from what i understood, he installed from .deb so the install dir should be good

**Comment by AugustoDeveloper** [comment]
> @christianparpart from what i understood, he installed from .deb so the install dir should be good
> 
> > ### Installer source
> > GitHub: release page

Yes, i installed contour by `.deb` file.

**Comment by AugustoDeveloper** [comment]
I really don't know if i'm doing somthing wrong cause don't works.

![image](https://github.com/contour-terminal/contour/assets/4335700/c38352a1-c91b-4a67-94eb-41425734401d)

**Comment by christianparpart** [comment]
> I really don't know if i'm doing somthing wrong cause i follow the instructions above and it doesn't works.
> 
> ![image](https://user-images.githubusercontent.com/4335700/241332927-c38352a1-c91b-4a67-94eb-41425734401d.png)

Looks like your directory structure is slightly off.

```sh
mkdir $HOME/.terminfo/c
mv $HOME/.terminfo/contour $HOME/.terminfo/c/contour
```

This moves the `contour` terminfo file from `$HOME/.terminfo/` to `$HOME/.terminfo/c/`. 

But shouldn't the terminfo file be properly installed from the .deb file already?
If not, we must fix that (I'm on smartphone right now, will check asap)

**Comment by AugustoDeveloper** [comment]
> > I really don't know if i'm doing somthing wrong cause i follow the instructions above and it doesn't works.
> > ![image](https://user-images.githubusercontent.com/4335700/241332927-c38352a1-c91b-4a67-94eb-41425734401d.png)
> 
> Looks like your directory structure is slightly off.
> 
> ```shell
> mkdir $HOME/.terminfo/c
> mv $HOME/.terminfo/contour $HOME/.terminfo/c/contour
> ```
> 
> This moves the `contour` terminfo file from `$HOME/.terminfo/` to `$HOME/.terminfo/c/`.
> 
> But shouldn't the terminfo file be properly installed from the .deb file already? If not, we must fix that (I'm on smartphone right now, will check asap)

Sorry, it doesn't works.
![image](https://github.com/contour-terminal/contour/assets/4335700/ec7f7258-eaae-42a5-9376-00ccf6ecfd69)

**Comment by AugustoDeveloper** [comment]
Debugging my console app on `JetBrains Rider` the errors ocurrs when `Evaluate` method is called.

[Reference: Line 207](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Console/src/System/ConsolePal.Unix.cs)
```csharp

        public static string Title
        {
            get { throw new PlatformNotSupportedException(); }
            set
            {
                if (Console.IsOutputRedirected)
                    return;

                string? titleFormat = TerminalFormatStringsInstance.Title;
                if (!string.IsNullOrEmpty(titleFormat))
                {
                    string ansiStr = TermInfo.ParameterizedStrings.Evaluate(titleFormat, value); // Error occurs when call this line
                    WriteStdoutAnsiString(ansiStr, mayChangeCursorPosition: false);
                }
            }
        }
```
I'll show the situation when debug is on `gnome-terminal`  and on `contour`.

## Gnome Terminal
![image](https://github.com/contour-terminal/contour/assets/4335700/c35c6aa9-dffc-4605-b1ee-d03770f41b40)
![image](https://github.com/contour-terminal/contour/assets/4335700/e847409f-1bbc-4cde-9da9-67111662e510)
![image](https://github.com/contour-terminal/contour/assets/4335700/1f728a03-da7a-468c-af01-cdcbf5b7b2d8)
![image](https://github.com/contour-terminal/contour/assets/4335700/b512c7df-ace9-4838-b8ba-7c8c30dbb434)
![image](https://github.com/contour-terminal/contour/assets/4335700/3b19f1c3-b5a3-4b4c-b9dd-ca3412751e5d)
![image](https://github.com/contour-terminal/contour/assets/4335700/2ad86d50-dcf7-462b-a4a7-064ec9e0c77f)

After all that, no error is thrown and call method to apply new title `WriteStdoutAnsiString`.

## Contour
![image](https://github.com/contour-terminal/contour/assets/4335700/d18afe11-5fb4-4b90-8745-4485254bcffa)
![image](https://github.com/contour-terminal/contour/assets/4335700/0ed5c323-3e7e-4a5a-96b1-3ba1ed5af8de)
![image](https://github.com/contour-terminal/contour/assets/4335700/b13e091d-f974-4539-b67d-3a6a4cb9f50b)
![image](https://github.com/contour-terminal/contour/assets/4335700/58387dcd-454a-43f2-8217-66385f46a88a)

The error throws at line [131](https://github.com/dotnet/runtime/blob/d58754bcbd414461adfc5ffb8f2b6c89f078cd12/src/libraries/System.Console/src/System/TermInfo.cs#L131):
![image](https://github.com/contour-terminal/contour/assets/4335700/fdbf466e-16ad-4989-8f4b-37d03ae5d50c)
![image](https://github.com/contour-terminal/contour/assets/4335700/a93e761f-5323-451f-8610-8bfbdf0c8b65)

You can see some variables value here:
```csharp
format = "[2$~[1$}[1;%dH%p1%s[$}"
pos = 15
```
![image](https://github.com/contour-terminal/contour/assets/4335700/e9d63a92-1250-4352-bcc5-96f58829a1af)

I can't debug much further than the above line, the exception occurs after attempt to step into it. Looking the code, the first character into the `format` variable should be , as the `Gnome Terminal` scenario, `p` to make `Push`  a parameter, but the `d` is found, making a `Pop` from an empty stack.

Sorry for  bunch of prints, but i hope to give you some insights to resolve this problem.

**Comment by Utkarsh-khambra** [comment]
Could you share your terminfo file that it's picking up, so that I can test with that as well. Also vt sequence trace when this application is running will also be good i.e  you'll need to  invoke contour with `contour debug vt.trace.sequence` and save that output to somewhere.

**Comment by christianparpart** [comment]
To summarise the Discord's outcome.

- the terminfo used is a bit old (we really need to create a new point release ASAP)
- the old terminfo wasn't bad though, but it is expecting two parameters to be passed, with the second one being a column to start writing to in the status line (since `tsl` stands for "to status line" and was only **abused** by xterm and the likes to set the window title, which is wrong to begin with)
- there is varying documentation, some saying %d does pop from stack, others say it doesn't.
- however, dotnet should probably not hard-fail on internal (and especially recoverable) errors, but instead fallback when not being able to set the title. External data (e.g. unexpected terminfo entries) should not cause your application to crash :)

We've fixed the problem for @AugustoDeveloper  by providing an up-to-date terminfo file (which contains a more trivialized form of `tsl` to move to the (host writable) status line, which also does not imply 2 parameters on the stack anymore.

But it also showed that we really should create a new bugfix release ASAP. :)
