### ISSUE TITLE
Box drawing may cause a freeze (infinite loop) in pixmap construction.

### ISSUE THREAD

**Issue by dankamongmen** [contour-terminal/contour#463]
## Description

This has been happening for about a week now. Current build is `0.2.1-unreleased-master-03989d6`. When I run `notcurses-info`, Contour locks up (livelock, CPU is pegged) after printing the initial banner (picture below). In the console, I have the following output:

```
[vt.parser:Sequencer.cpp:1271] Unknown VT sequence: CSI > u
[vt.parser:Sequencer.cpp:1271] Unknown VT sequence: CSI > 2;1 m
[vt.parser:Sequencer.cpp:1271] Unknown VT sequence: CSI > 4;1 m
[vt.parser:Sequencer.cpp:1271] Unknown VT sequence: CSI = 11 u
[vt.parser:Sequencer.cpp:1304] Unsupported VT sequence: CSI = c
[vt.parser:Sequencer.cpp:1271] Unknown VT sequence: CSI ? u
[vt.parser:Sequencer.cpp:1301] Invalid VT sequence: CSI ? 8452 h
[vt.parser:Sequencer.cpp:1304] Unsupported VT sequence: CSI > 1 s
[error] Failed to FT_Select_Size(index=0, source path /usr/share/fonts/truetype/babelstone/BabelStoneHan.ttf): invalid face handle
[error] Failed to FT_Set_Char_Size(size=768, dpi (110, 110), source path /usr/share/fonts/X11/misc/cu-pua12.pcf.gz): invalid pixel size
[error] Failed to FT_Set_Char_Size(size=768, dpi (110, 110), source path /usr/share/fonts/truetype/unifont/unifont_sample.ttf): invalid pixel size
```

Contour is in the upper left, launched from the terminal in the center:

![2021-10-16-013014_3440x1440_scrot](https://user-images.githubusercontent.com/143473/137575105-e6be9d2a-b5ec-46f9-bce8-f1fcfe187977.png)

## Environment

- Contour Version or Git commit hash: 03989d68f38a1fd11f33671505a892136f9754b8
- Operating System (name / distribution / version): Debian Unstable
- Contour configuration: default, i think
- TERM environment variable: 
```
declare -x TERM="xterm-256color"
declare -x TERMINAL_NAME="contour"
declare -x TERMINAL_VERSION_STRING="0.2.1-unreleased-master-03989d6"
declare -x TERMINAL_VERSION_TRIPLE="0.2.1"
declare -x TERMINFO="/home/dank/src/dankamongmen/kitty/terminfo"
```
- Compiler version:
- `gcc version 11.2.0 (Debian 11.2.0-9)`

**Comment by christianparpart** [comment]
Lol what. I will check. Thank you

**Comment by christianparpart** [comment]
Since about s week you said? Hmm...  S while guess it's that it is caused by one of the box drawing improvements, somewhere some infinite loop.

Would you mind sharing a  stack trace for me?

**Comment by dankamongmen** [comment]
yeah let me see what i can do

**Comment by dankamongmen** [comment]
```c
^C
Thread 1 "contour" received signal SIGINT, Interrupt.
terminal::renderer::detail::(anonymous namespace)::Pixmap::paint (_value=<optimized out>, y=<optimized out>, x=<optimized out>, this=<optimized out>) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:596
596	       auto const w = unbox<int>(_size.width);
(gdb) bt
#0  terminal::renderer::detail::(anonymous namespace)::Pixmap::paint (_value=<optimized out>, y=<optimized out>, x=<optimized out>, this=<optimized out>) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:596
#1  terminal::renderer::detail::(anonymous namespace)::Pixmap::segment_line (to=..., from=..., base=..., orientation=terminal::renderer::detail::(anonymous namespace)::Pixmap::Orientation::Vertical, this=0x7fffffffc240) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:637
#2  terminal::renderer::detail::(anonymous namespace)::Pixmap::segment_bar(int) (this=this@entry=0x7fffffffc240, which=which@entry=2) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:551
#3  0x000000000059f39d in terminal::renderer::detail::(anonymous namespace)::Pixmap::segment_bar<int, int, int, int> (which=2, this=0x7fffffffc240) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:564
#4  terminal::renderer::detail::(anonymous namespace)::Pixmap::segment_bar<int, int, int, int, int> (which=1, this=0x7fffffffc240) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:567
#5  terminal::renderer::BoxDrawingRenderer::buildElements(char32_t) (this=0x867b28, codepoint=<optimized out>) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:1534
#6  0x00000000005aa33b in terminal::renderer::BoxDrawingRenderer::getDataRef(char32_t) (this=0x867b28, codepoint=<optimized out>) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:1054
#7  0x00000000005aa85a in terminal::renderer::BoxDrawingRenderer::render(crispy::boxed<int, terminal::detail::tags::LinePosition>, crispy::boxed<int, terminal::detail::tags::Column>, char32_t, terminal::RGBColor) (this=this@entry=0x867b28, _line=..., _column=..., _codepoint=<optimized out>, _color=...) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:1021
#8  0x00000000005bcf56 in terminal::renderer::TextRenderer::renderCell(terminal::RenderCell const&) (this=this@entry=0x867aa0, _cell=...) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/TextRenderer.cpp:137
#9  0x00000000005b135a in terminal::renderer::Renderer::renderCells(std::vector<terminal::RenderCell, std::allocator<terminal::RenderCell> > const&) (this=this@entry=0x8677d8, _renderableCells=<optimized out>) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/Renderer.cpp:340
#10 0x00000000005b14b1 in terminal::renderer::Renderer::render(terminal::Terminal&, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, bool) (this=this@entry=0x8677d8, _terminal=..., _now=..., _pressure=_pressure@entry=false) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/Renderer.cpp:290
#11 0x000000000058a897 in contour::opengl::TerminalWidget::paintGL() (this=0x867750) at /home/dank/src/dankamongmen/contour/src/contour/opengl/TerminalWidget.cpp:449
#12 0x00007ffff78edb7d in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff78ce7ae in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x000000000058f0f8 in contour::opengl::TerminalWidget::event(QEvent*) (this=0x867750, _event=0x7fffffffc700) at /home/dank/src/dankamongmen/contour/src/contour/opengl/TerminalWidget.cpp:571
#15 0x00007ffff788c74f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff6b97e9a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff78c67b6 in QWidgetPrivate::sendPaintEvent(QRegion const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff789dbd5 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff78cef05 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff788c74f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff6b97e9a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff6b9ae11 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff6bf0413 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff6216d0b in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff6216fb8 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff621706f in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff6befa90 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007ffff6b968db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007ffff6b9eb10 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00000000004da1a8 in contour::terminalGUI(int, char const**, crispy::cli::FlagStore const&) (argc=<optimized out>, argv=0x7fffffffde48, _flags=...) at /home/dank/src/dankamongmen/contour/src/contour/ContourGuiApp.cpp:197
#31 0x00000000005c8a3c in std::function<int ()>::operator()() const (this=0x6bb7c0) at /usr/include/c++/11/bits/std_function.h:560
#32 crispy::App::run(int, char const**) (this=this@entry=0x7fffffffdb70, argc=argc@entry=1, argv=argv@entry=0x7fffffffde48) at /home/dank/src/dankamongmen/contour/src/crispy/App.cpp:284
#33 0x00000000004d58b2 in contour::ContourGuiApp::run(int, char const**) (this=this@entry=0x7fffffffdb70, argc=argc@entry=1, argv=argv@entry=0x7fffffffde48) at /home/dank/src/dankamongmen/contour/src/contour/ContourGuiApp.cpp:54
#34 0x000000000048b4bb in main(int, char const**) (argc=1, argv=0x7fffffffde48) at /home/dank/src/dankamongmen/contour/src/contour/main.cpp:24
(gdb) thread apply all bt

Thread 6 (Thread 0x7fffea209640 (LWP 992544) "contour"):
#0  0x00007ffff64ac543 in __GI___select (nfds=14, readfds=0x7fffea208210, writefds=0x7fffea208290, exceptfds=0x7fffea208310, timeout=0x7fffea2080c0) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x00000000005413eb in terminal::UnixPty::read(unsigned long, std::chrono::duration<long, std::ratio<1l, 1000l> >) (this=0x8d9110, _size=16384, _timeout=...) at /home/dank/src/dankamongmen/contour/src/terminal/pty/UnixPty.cpp:201
#2  0x00000000004fc01f in terminal::PtyProcess::read(unsigned long, std::chrono::duration<long, std::ratio<1l, 1000l> >) (this=<optimized out>, _size=<optimized out>, _timeout=...) at /home/dank/src/dankamongmen/contour/src/terminal/pty/PtyProcess.cpp:61
#3  0x0000000000538cb3 in terminal::Terminal::processInputOnce() (this=0xa265d8) at /home/dank/src/dankamongmen/contour/src/terminal/Terminal.cpp:168
#4  0x0000000000539b40 in terminal::Terminal::mainLoop() (this=0xa265d8) at /home/dank/src/dankamongmen/contour/src/terminal/Terminal.cpp:153
#5  0x00007ffff67b08c4 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7710eae in start_thread (arg=0x7fffea209640) at pthread_create.c:463
#7  0x00007ffff64b4a5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fffeb7fe640 (LWP 992524) "contour"):
#0  0x00007ffff6481c87 in __GI___wait4 (pid=992523, stat_loc=0x7fffeb7fdc8c, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
#1  0x000000000050b0d7 in terminal::Process::checkStatus(bool) const (this=0x8d8a00, _waitForExit=<optimized out>) at /home/dank/src/dankamongmen/contour/src/terminal/Process.cpp:371
#2  0x000000000050b24e in terminal::Process::wait() (this=<optimized out>) at /home/dank/src/dankamongmen/contour/src/terminal/Process.cpp:420
#3  0x00000000004fc095 in operator() (__closure=0x8d8a58) at /home/dank/src/dankamongmen/contour/src/terminal/pty/PtyProcess.cpp:24
#4  std::__invoke_impl<void, terminal::PtyProcess::PtyProcess(const ExecInfo&, terminal::PageSize, std::optional<crispy::ImageSize>)::<lambda()> > (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#5  std::__invoke<terminal::PtyProcess::PtyProcess(const ExecInfo&, terminal::PageSize, std::optional<crispy::ImageSize>)::<lambda()> > (__fn=...) at /usr/include/c++/11/bits/invoke.h:96
#6  std::thread::_Invoker<std::tuple<terminal::PtyProcess::PtyProcess(const ExecInfo&, terminal::PageSize, std::optional<crispy::ImageSize>)::<lambda()> > >::_M_invoke<0> (this=0x8d8a58) at /usr/include/c++/11/bits/std_thread.h:253
#7  std::thread::_Invoker<std::tuple<terminal::PtyProcess::PtyProcess(const ExecInfo&, terminal::PageSize, std::optional<crispy::ImageSize>)::<lambda()> > >::operator() (this=0x8d8a58) at /usr/include/c++/11/bits/std_thread.h:260
#8  std::thread::_State_impl<std::thread::_Invoker<std::tuple<terminal::PtyProcess::PtyProcess(const ExecInfo&, terminal::PageSize, std::optional<crispy::ImageSize>)::<lambda()> > > >::_M_run(void) (this=0x8d8a50) at /usr/include/c++/11/bits/std_thread.h:211
#9  0x00007ffff67b08c4 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007ffff7710eae in start_thread (arg=0x7fffeb7fe640) at pthread_create.c:463
#11 0x00007ffff64b4a5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fffebfff640 (LWP 992522) "QDBusConnection"):
#0  0x00007ffff64a9e2f in __GI___poll (fds=0x7fffe0003170, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff6216f4e in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff621706f in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff6befa90 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff6b968db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff69b41be in QThread::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff336a647 in  () at /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#7  0x00007ffff69b5301 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff7710eae in start_thread (arg=0x7fffebfff640) at pthread_create.c:463
#9  0x00007ffff64b4a5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7ffff0e4b640 (LWP 992521) "QThread"):
#0  0x00007ffff64a9e2f in __GI___poll (fds=0x7fffe4002a00, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff6216f4e in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff621706f in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff6befa90 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff6b968db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff69b41be in QThread::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff69b5301 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff7710eae in start_thread (arg=0x7ffff0e4b640) at pthread_create.c:463
#8  0x00007ffff64b4a5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7ffff2980640 (LWP 992333) "QXcbEventQueue"):
#0  0x00007ffff64a9e2f in __GI___poll (fds=0x7ffff297fc08, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff3b14d02 in  () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007ffff3b1705a in xcb_wait_for_event () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007ffff34504b0 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007ffff69b5301 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff7710eae in start_thread (arg=0x7ffff2980640) at pthread_create.c:463
#6  0x00007ffff64b4a5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff38d0800 (LWP 992059) "contour"):
#0  terminal::renderer::detail::(anonymous namespace)::Pixmap::paint (_value=<optimized out>, y=<optimized out>, x=<optimized out>, this=<optimized out>) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:596
#1  terminal::renderer::detail::(anonymous namespace)::Pixmap::segment_line (to=..., from=..., base=..., orientation=terminal::renderer::detail::(anonymous namespace)::Pixmap::Orientation::Vertical, this=0x7fffffffc240) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:637
#2  terminal::renderer::detail::(anonymous namespace)::Pixmap::segment_bar(int) (this=this@entry=0x7fffffffc240, which=which@entry=2) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:551
#3  0x000000000059f39d in terminal::renderer::detail::(anonymous namespace)::Pixmap::segment_bar<int, int, int, int> (which=2, this=0x7fffffffc240) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:564
#4  terminal::renderer::detail::(anonymous namespace)::Pixmap::segment_bar<int, int, int, int, int> (which=1, this=0x7fffffffc240) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:567
#5  terminal::renderer::BoxDrawingRenderer::buildElements(char32_t) (this=0x867b28, codepoint=<optimized out>) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:1534
#6  0x00000000005aa33b in terminal::renderer::BoxDrawingRenderer::getDataRef(char32_t) (this=0x867b28, codepoint=<optimized out>) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:1054
#7  0x00000000005aa85a in terminal::renderer::BoxDrawingRenderer::render(crispy::boxed<int, terminal::detail::tags::LinePosition>, crispy::boxed<int, terminal::detail::tags::Column>, char32_t, terminal::RGBColor) (this=this@entry=0x867b28, _line=..., _column=..., _codepoint=<optimized out>, _color=...) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:1021
#8  0x00000000005bcf56 in terminal::renderer::TextRenderer::renderCell(terminal::RenderCell const&) (this=this@entry=0x867aa0, _cell=...) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/TextRenderer.cpp:137
#9  0x00000000005b135a in terminal::renderer::Renderer::renderCells(std::vector<terminal::RenderCell, std::allocator<terminal::RenderCell> > const&) (this=this@entry=0x8677d8, _renderableCells=<optimized out>) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/Renderer.cpp:340
#10 0x00000000005b14b1 in terminal::renderer::Renderer::render(terminal::Terminal&, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, bool) (this=this@entry=0x8677d8, _terminal=..., _now=..., _pressure=_pressure@entry=false) at /home/dank/src/dankamongmen/contour/src/terminal_renderer/Renderer.cpp:290
#11 0x000000000058a897 in contour::opengl::TerminalWidget::paintGL() (this=0x867750) at /home/dank/src/dankamongmen/contour/src/contour/opengl/TerminalWidget.cpp:449
#12 0x00007ffff78edb7d in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff78ce7ae in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x000000000058f0f8 in contour::opengl::TerminalWidget::event(QEvent*) (this=0x867750, _event=0x7fffffffc700) at /home/dank/src/dankamongmen/contour/src/contour/opengl/TerminalWidget.cpp:571
#15 0x00007ffff788c74f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff6b97e9a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff78c67b6 in QWidgetPrivate::sendPaintEvent(QRegion const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff789dbd5 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff78cef05 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff788c74f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff6b97e9a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff6b9ae11 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff6bf0413 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff6216d0b in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff6216fb8 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff621706f in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff6befa90 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007ffff6b968db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007ffff6b9eb10 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00000000004da1a8 in contour::terminalGUI(int, char const**, crispy::cli::FlagStore const&) (argc=<optimized out>, argv=0x7fffffffde48, _flags=...) at /home/dank/src/dankamongmen/contour/src/contour/ContourGuiApp.cpp:197
#31 0x00000000005c8a3c in std::function<int ()>::operator()() const (this=0x6bb7c0) at /usr/include/c++/11/bits/std_function.h:560
#32 crispy::App::run(int, char const**) (this=this@entry=0x7fffffffdb70, argc=argc@entry=1, argv=argv@entry=0x7fffffffde48) at /home/dank/src/dankamongmen/contour/src/crispy/App.cpp:284
#33 0x00000000004d58b2 in contour::ContourGuiApp::run(int, char const**) (this=this@entry=0x7fffffffdb70, argc=argc@entry=1, argv=argv@entry=0x7fffffffde48) at /home/dank/src/dankamongmen/contour/src/contour/ContourGuiApp.cpp:54
#34 0x000000000048b4bb in main(int, char const**) (argc=1, argv=0x7fffffffde48) at /home/dank/src/dankamongmen/contour/src/contour/main.cpp:24
(gdb) 
```

**Comment by christianparpart** [comment]
I could repro it. But only by eliminating the guard to not allow any font size below 5pt (I did set it to 1pt minimum). This is most likely because I'm on 4k screen large DPI numbers. My guess is you are having smaller DPI values resulting in smaller pixel heights that could have caused this infinite loop.

**Comment by dankamongmen** [comment]
hrmmmm. my monitor is 3440x1440, not too small. DPI is 96x96.

**Comment by dankamongmen** [comment]
you're certain it has nothing to do with my font selections?

**Comment by dankamongmen** [comment]
fix confirmed, nice work homie
